[python]
python_interpreter = "C:\\Users\\Ananthapriyan M\\AppData\\Local\\Programs\\Python\\Python314\\python.exe"
search_path = [
    "C:\\Users\\Ananthapriyan M\\AppData\\Local\\Programs\\Python\\Python314\\Lib\\site-packages",
    "c:\\Users\\Ananthapriyan M\\Downloads\\cloudvuln\\backend"
]
